/*
Copyright 2025 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

import (
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kubeclient "knative.dev/pkg/client/injection/kube/client"
	"knative.dev/pkg/ptr"
	"knative.dev/pkg/system"
)

// PrunerConfigMapName  This function is added to backward compatibility from Tech Preview.
// All the errors generated by this function will be ignored.
func (pc *PrunerConfig) setDefaultFromConfigMap(ctx context.Context) {
	// If ConfigMap is present then  set the default values as defined in map
	kubeClient := kubeclient.Get(ctx)
	namespace := system.Namespace()

	// Load config from ConfigMap
	configMap, err := kubeClient.CoreV1().ConfigMaps(namespace).Get(ctx, PrunerConfigMapName, metav1.GetOptions{})
	if err == nil {
		// If the ConfigMap is found, we can load the values into the PrunerConfig
		if err := PrunerConfigStore.LoadGlobalConfig(ctx, configMap); err == nil {
			// Now set the defaults based on the loaded config
			globalConfig := PrunerConfigStore.globalConfig
			pc.EnforcedConfigLevel = globalConfig.EnforcedConfigLevel
			pc.TTLSecondsAfterFinished = globalConfig.TTLSecondsAfterFinished
			pc.SuccessfulHistoryLimit = globalConfig.SuccessfulHistoryLimit
			pc.FailedHistoryLimit = globalConfig.FailedHistoryLimit
			pc.HistoryLimit = globalConfig.HistoryLimit
		}

	}
}

func (pc *PrunerConfig) SetDefaults() {
	pc.setDefaultFromConfigMap(context.Background())
	if pc.HistoryLimit == nil {
		pc.HistoryLimit = ptr.Int32(DefaultHistoryLimit)
	}
	if pc.EnforcedConfigLevel == nil {
		v := EnforcedConfigLevelGlobal
		pc.EnforcedConfigLevel = &v
	}
}
